version: '3.3'
services:
  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - reddit

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      -  '9090:9090'
    networks:
      - reddit
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:2.0
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - reddit
volumes:
  post_db:

networks:
  reddit:
